//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Great.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalHistory
    {
        public int Id { get; set; }
        public int Car { get; set; }
        public int StartKm { get; set; }
        public Nullable<int> EndKm { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte StartFuelLevel { get; set; }
        public Nullable<byte> EndFuelLevel { get; set; }
        public string Notes { get; set; }
    
        public virtual Car Car1 { get; set; }
    }
}
