//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Great.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarRentalCompany> CarRentalCompany { get; set; }
        public virtual DbSet<CarRentalHistory> CarRentalHistory { get; set; }
        public virtual DbSet<ExpenseAccount> ExpenseAccount { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<FDL> FDL { get; set; }
        public virtual DbSet<Timesheet> Timesheet { get; set; }
    }
}
