//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Great.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAccount
    {
        public long Id { get; set; }
        public long FDL { get; set; }
    
        public virtual FDL FDL1 { get; set; }
    }
}
