//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Great.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseAccount()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public long Id { get; set; }
        public string FDL { get; set; }
        public Nullable<long> CdC { get; set; }
        public string Currency { get; set; }
        public long Status { get; set; }
        public string LastError { get; set; }
        public string FileName { get; set; }
        public bool NotifyAsNew { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual FDLStatu FDLStatu { get; set; }
        public virtual FDL FDL1 { get; set; }
    }
}
